#!/bin/bash

set -e

service=frontend
remote_user=root
remote_host=51.15.116.61

echo "[DEPLOY] Running deploy for $service"

echo "[DEPLOY] Creating Package $service.tar.gz"

rm -rf $service.tar.gz
tar -czf $service.tar.gz -C $(pwd)/$service .

echo "[DEPLOY] Delivering package to server"

ssh $remote_user@$remote_host "rm -rf /tmp/$service" 
scp $service.tar.gz $remote_user@$remote_host:/tmp

ssh $remote_user@$remote_host "rm -rf /opt/${service}"
ssh $remote_user@$remote_host "mkdir /opt/${service}"
ssh $remote_user@$remote_host "tar -xzf /tmp/${service}.tar.gz -C /opt/${service}"
